### ISSUE TITLE
the project plan

### ISSUE THREAD

**Issue by zqb-all** [howjmay/neon2rvv#1]
Hi, from the name of the project, it seems that it is planned to be something like [sse2neon](https://github.com/DLTcollab/sse2neon), isn't it ?

**Comment by howjmay** [comment]
Yes. I was busy for other things. Let me arrange sometime to give this a try

**Comment by zqb-all** [comment]
Thanks for your reply. This will be helpful for software compatibility on the riscv platform

**Comment by howjmay** [comment]
Thank you! But a lot of things I am still trying to figure out now
